### ISSUE TITLE
JSONDecodeError when trying to analyse file with multi-line string

### ISSUE THREAD

**Issue by ahayzen** [flathub-infra/flatpak-external-data-checker#1]
When trying to check com.spotify.Client.json I get the following decode error.
```
./flatpak-external-data-checker ~/Downloads/com.spotify.Client.json --filter-type extra-data
Traceback (most recent call last):
  File "./flatpak-external-data-checker", line 70, in <module>
    manifest_checker = checker.ManifestChecker(args.manifest)
  File "/home/andrew/Workspace/Projects/flatpak/external-data-checker/jrocha/flatpak-external-data-checker/src/checker.py", line 43, in __init__
    self._json_data = json.loads(clean_manifest, object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 185 column 71 (char 6593)
```

This seems to be due to the `\n` or multi-line string in the JSON https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L185

Maybe the python json lib is not acting the same as C here ? Or we need to pass some option ?

**Comment by ahayzen** [comment]
@wjt Does your commit "Handle JSON files with multi-line strings" from https://github.com/joaquimrocha/flatpak-external-data-checker/pull/10 fix this issue ? (it seems to for me)

**Comment by wjt** [comment]
Yes, that's the idea – it parses the "JSON" file using exactly the same parser (which accepts this illegal syntax)
