### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by Zlopez** [flathub-infra/flatpak-external-data-checker#109]
Hi,

I don't know how to contact you by other means, so I just left it here.

I wanted to just say thank you for your work. This project is really helpful. And as a maintainer of Anitya project I'm glad that you integrated the Anitya checker in your project. I wanted to create a notifier for it by myself, but didn't found the time to finish it.

So thank you for all the work.

**Comment by Zlopez** [comment]
Just a note, I recently released [Anitya 1.0.0](https://github.com/fedora-infra/anitya/releases/tag/1.0.0) with plenty of changes, maybe some of them could be interesting for you.

**Comment by gasinvein** [comment]
Thank _you_ for the release-monitoring.org project.

>maybe some of them could be interesting for you

We'll definitely be interested in pre-release flags. Are they exposed in API?

**Comment by Zlopez** [comment]
Unfortunately not now, they are only exposed in the message that is emitted when new version is found. Didn't thought about adding this info to API, but it should be easy to add them. I could also recommend to use API v2 `/api/v2/versions/`, it's newly added and more robust than API v1.

I created an issue for exposing the stable versions: https://github.com/fedora-infra/anitya/issues/1014

**Comment by gasinvein** [comment]
Thanks, I'll add an option to use only stable versions once `stable_versions` is exposed.
v2 url with versions for a single project should be `/api/v2/versions/?project_id=NNN`, right?

**Comment by Zlopez** [comment]
Yes, here you can look at the [documentation](https://anitya.readthedocs.io/en/stable/api.html#get--api-v2-versions-)

**Comment by Zlopez** [comment]
The https://github.com/fedora-infra/anitya/issues/1014 is now implemented and the new version is running in production. Feel free to use this :-)

**Comment by gasinvein** [comment]
Thanks! Any ETA of landing this changes on release-monitoring.org?

**Comment by Zlopez** [comment]
There are already live there
