### ISSUE TITLE
Whole files are stored in memory

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#126]
Currently we need whole file contents just for AppImage version extraction.
Keeping large files in memory can obviously result in OOM, like https://github.com/flathub/flatpak-external-data-checker/issues/88#issuecomment-648116372.
Also we may need to do something with downloaded files in future, e.g. run flatpak-builder-tools against them.

**Comment by wjt** [comment]
```python3
with tempfile.TemporaryDirectory() as workdir:
    manifest_checker = checker.ManifestChecker(args.manifest, workdir)
    ....
```

or so?

**Comment by gasinvein** [comment]
I was thinking about storing downloads in `$XDG_CACHE_HOME`. `/tmp` is usually on tmpfs, so, still in-memory.

**Comment by wjt** [comment]
You can tell `TemporaryDirectory` where to create its directory. The point of the context manager is a built-in way to clean up the directory on exit.

**Comment by gasinvein** [comment]
Right. But do we want to clean up files after run, though? Reusing existing downloads could significantly speedup subsequent runs.

**Comment by wjt** [comment]
Great point!

**Comment by gasinvein** [comment]
My primary concern is how to make sure that cached downloads don't get outdated. The same url can return different data.

**Comment by wjt** [comment]
It looks like there are a few adaptors for requests which implement caching and understand cache-related headers, such as https://cachecontrol.readthedocs.io/en/latest/ . That could be an option.
