### ISSUE TITLE
XML parse error when metainfo starts with a comment?

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#128]
flatpak-external-data-checker can't update `com.microsoft.Edge` (and probably some others apps) due to exception in XML parsing:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 2, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/src/main.py", line 301, in main
    if run_with_args(parse_cli_args()) > 0:
  File "/app/src/main.py", line 283, in run_with_args
    changes = manifest_checker.update_manifests()
  File "/app/src/checker.py", line 286, in update_manifests
    self._update_manifest(path, datas, changes)
  File "/app/src/checker.py", line 277, in _update_manifest
    appdata, last_update.version, timestamp.strftime("%F")
  File "/app/src/lib/appdata.py", line 139, in add_release_to_file
    add_release(appdata_path, buf, version, date)
  File "/app/src/lib/appdata.py", line 134, in add_release
    reader.parse(in_path_or_stream)
  File "/usr/lib/python3.7/xml/sax/saxutils.py", line 312, in parse
    self._parent.parse(source)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.7/xml/sax/saxutils.py", line 246, in fatalError
    self._err_handler.fatalError(exception)
  File "/usr/lib/python3.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: /github/workspace/flathub/com.microsoft.Edge/com.microsoft.Edge.metainfo.xml:2:0: XML or text declaration not at start of entity
```
I have no idea what's wrong. Comment on the first line of an XML file should be fine, shouldn't it?

**Comment by TheEvilSkeleton** [comment]
> consider moving the copyright comment in `.metainfo.xml` to the second line.

https://github.com/flathub/com.microsoft.Edge/issues/17#issue-810478379

That was the fix.

**Comment by wjt** [comment]
The problem isn't the comment as such, but that the XML declaration (if present) must be the first thing in the file, with the possible exception of a byte-order mark. https://www.liquid-technologies.com/XML/Declaration.aspx among other pages documents this.

So I think this is working as expected™ though it could be handled more gracefully. If you're feeling brave you could add more aggravating hacks in `appdata.py` (though see it, 00ca048ed1ae6f7817627d37bd4424a74d03a7d0's commit message and the tests for the lengths already gone to to deal with wacky XML). I thought I had added an expectedFailure test case for this but I guess not.

**Comment by gasinvein** [comment]
The thing is, appstream-glib considers this fine. But if it's really invalid - I agree we shouldn't try handle it, then. Maybe just skip appdata update in case of parse exception?

**Comment by wjt** [comment]
Sounds good. Perhaps with a note in the commit message that it couldn't be updated due to a parse error?

**Comment by TheEvilSkeleton** [comment]
Fyi GNOME Builder complains about it as well:

![image](https://user-images.githubusercontent.com/50847364/108270052-e3472880-713c-11eb-8fd6-257777f49b33.png)

**Comment by gasinvein** [comment]
I'd say appstream-glib shouldn't permit it, too, then.

**Comment by gasinvein** [comment]
Opened #129 (I've ended up also rewriting appdata file detection logic)
