### ISSUE TITLE
Incomplete HTTP read is ignored

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#142]
In past week, flatpak-external-data-checker submitted several PRs (e.g. flathub/com.wps.Office#96) to WPS Office flatpak where the checksum (and only it) was changed. The "new" checksum is different each time and seems invalid - re-checking showed that the checksum didn't actually change.
It doesn't look like partial read, since the size doesn't change, and no http error occurs.

**Comment by wjt** [comment]
Isn't the size taken from the content-length header? This sounds like short read to me.

**Comment by gasinvein** [comment]
Oh, looks like it is taken from headers indeed:
https://github.com/flathub/flatpak-external-data-checker/blob/0e025df7c60b6c75dc85a6962e85220c6e391730/src/lib/utils.py#L108-L109

How do we catch partial read?

**Comment by wjt** [comment]
Compare length of data read to content-length header?

**Comment by gasinvein** [comment]
The supposed fix appeared to break other things rather badly and was reverted, so I'm reopening this.

**Comment by gasinvein** [comment]
I can't reproduce it with httpbin sample. Opening `https://httpbingo.org/response-headers?Content-Length=200` with `requests.get()` raises `ChunkedEncodingError`. Does this mean that's incomplete read error is ignored only in some specific cases?

**Comment by gasinvein** [comment]
The most recent WPS Office update log that resulted in changed checksum:
```
+ 2021-03-04 02:44:10,845   DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): wdl1.pcfg.cache.wpscdn.com:443
+ 2021-03-04 02:44:15,547   DEBUG urllib3.connectionpool: https://wdl1.pcfg.cache.wpscdn.com:443 "GET /wpsdl/wpsoffice/download/linux/10161/wps-office_11.1.0.10161.XA_amd64.deb HTTP/1.1" 200 228984666
+ 2021-03-04 02:44:46,184    INFO src.lib.externaldata: Source wps-office.deb: got new version 11.1.0.10161
```
Note the size `228984666` in HTTP GET debug line. It's the same size as the one stored in manifest. So maybe it's not incomplete read after all?

**Comment by gasinvein** [comment]
Looks like httpbingo behaves differently from what we expect (and from httpbin). `/response-headers` with invalid `Content-Length` causes it to close connection instead of returning proper response with invalid header.

httpbin:
```
$ curl "https://httpbin.org/response-headers?Content-Length=1000"
{
  "Content-Length": [
    "91", 
    "1000"
  ], 
  "Content-Type": "application/json"
}
curl: (18) transfer closed with 909 bytes remaining to read
```
httpbingo:
```
$ curl "https://httpbingo.org/response-headers?Content-Length=1000"
curl: (92) HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
{"Content-Length":["1000"]}
```

**Comment by gasinvein** [comment]
I've committed a rather blunt check that should prevent incomplete reads from propagating (in https://github.com/flathub/flatpak-external-data-checker/commit/e1f11ca8b9bec1a8ab4963133a14d5832acb4434). However, it doesn't retry downloading, so I'm leaving this issue open until we come up with a better solution.
