### ISSUE TITLE
flathubbot not automatically merging

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub-infra/flatpak-external-data-checker#149]
We got an MR from flathubbot, but it still needed manually merging, see https://github.com/flathub/com.brave.Browser/pull/23.

However, I've enabled automerging, see [com.brave.Browser's `flathub.json`](https://github.com/flathub/com.brave.Browser/blob/beta/flathub.json#L5-L6).

I'm not sure exactly what the issue is. Perhaps I wrote it wrongly?

**Comment by gasinvein** [comment]
Yes, the `automerge-flathubbot-prs` property in your `flathub.json` is invalid, should be `true` instead of `[ true ]` (boolean instead of list).

**Comment by TheEvilSkeleton** [comment]
```json
{
  "only-arches": [
    "x86_64"
  ],
  "automerge-flathubbot-prs":
    true
}
```

Like this?

**Comment by gasinvein** [comment]
Almost, the new line is redundant (I'm not sure if it'll result in parse error or not, but better not adding it).

**Comment by TheEvilSkeleton** [comment]
```json
{
  "only-arches": [
    "x86_64"
  ],
  "automerge-flathubbot-prs": true
}
```

This should be right, right?

**Comment by gasinvein** [comment]
Looks fine.

**Comment by TheEvilSkeleton** [comment]
Thank you.

**Comment by TheEvilSkeleton** [comment]
@gasinvein looks like I had to manually merge again: https://github.com/flathub/com.microsoft.Edge/pull/23. Should this be reopened?

**Comment by wjt** [comment]
This script only auto-merges if it finds an *existing* PR, with passing CI. IIRC it runs hourly.
