### ISSUE TITLE
Sourceforge round-robin servers create flood of updates

### ISSUE THREAD

**Issue by hadess** [flathub-infra/flatpak-external-data-checker#150]
The flathubbot that runs flatpak-external-data-checker created a flood of updates from version 6.5 to version 6.5 for Sweethome3D, while pointing to a slightly different tarball host each time.

These are the PRs created:
https://github.com/flathub/com.sweethome3d.Sweethome3d/pulls?q=is%3Apr+%226.5%22

And this is the `x-checker-data` field:
https://github.com/flathub/com.sweethome3d.Sweethome3d/blob/ee6fd8e4d491ebcbf11705b4b5b7589d0c9d3faf/com.sweethome3d.Sweethome3d.json#L38-L45

**Comment by gasinvein** [comment]
This can be fixed as easily as by disabling `follow_redirects` for `HTMLChecker` (and returning original url instead of real), but I'm not sure if there are no apps relying on current (IMO wrong) behavior. Ping @wjt @andrunko

**Comment by hadess** [comment]
https://github.com/flathub/flatpak-external-data-checker/pull/151 maybe?

**Comment by wjt** [comment]
I don't remember it being deliberate that HTMLChecker followed redirects. I know some of the others do follow redirects by design (specifically the rotating URL checker – that's its whole purpose).
