### ISSUE TITLE
Encoded content is decoded resulting in wrong size/checksum

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#159]
If I understood it right, flatpak expects raw http data for `extra-data`, i.e. if it has `Content-Encoding`, it's not taken into account and size and checkum apply to undecoded content. Probably this behavior depends on libcurl/libsoup?
Our http client automatically decodes content if it detects `Content-Encoding`, so we calculate size/checksum for decoded content, which is wrong for flatpak.
On Flathub I've found only one app with `gzip`'ed upstream URL for extra-data - [GravitDesigner](https://github.com/flathub/io.designer.GravitDesigner).

**Comment by gasinvein** [comment]
@wjt It appears to actually break GravitDesigner flatpak. What do you think, how we should fix this?
Passing `auto_decompress=False` should keep payload compressed, but this option is session-wide and [can't be set](https://github.com/aio-libs/aiohttp/issues/3751) for each request. And if we set it for the whole http session, it'll break APIs that actually send gzip-compressed text we need to read. Maybe set up two sessions: 1st for APIs and 2nd for downloads?

**Comment by wjt** [comment]
Sounds a good idea. It makes some conceptual sense because for the actual file downloads f-e-d-c is essentially pretending to be flatpak-builder, whereas for APIs and scraping random websites it is being itself / a browser

**Comment by gasinvein** [comment]
Creating two independent sessions will hurt performance, since they won't share connections. I've asked aiohttp devs (in the issue linked above) if it's ok to create a secondary session that reuses connection pool, cookies and whatnot from the primary session. They didn't respond yet, but from my local tests it seems to work fine. Should we proceed with this approach or wait for a response?

**Comment by gasinvein** [comment]
Now we have reverse problem: we calculate checksum for encoded content, which becomes invalid for flatpak-builder/libsoup when it receives non-encoded. See flathub/org.freedesktop.Sdk.Extension.php73#75 and flathub/org.octave.Octave#185

It feels like we just made it worse: we had 1 app the receives invalid update PRs, now we have 3 or even more.

**Comment by ranisalt** [comment]
> Passing `auto_decompress=False` should keep payload compressed, but this option is session-wide and [can't be set](https://github.com/aio-libs/aiohttp/issues/3751) for each request.

Now it does, and I have a file that **must** be downloaded with compression headers, otherwise it returns 403. Is it right to assume that for `type: extra-data` then `auto_decompress=False`, and `True` otherwise?
