### ISSUE TITLE
Stop checking file/archive sources without x-checker-data?

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#169]
Currently we download all the sources specified in the manifest and compare checksums. But is this really needed?
`extra-data` type sources need to be periodically validated, 'cause the checksum change will result in non installable apps. But this doesn't apply to "normal" sources that are downloaded at build time.
From what I can tell, validating "normal" sources mostly causes problems, propagating check error like #168 and #142 to apps that didn't even ask to be checked.
So, I think we should consider limiting implicitly enabled validation to extra-data type sources only.
This would also significantly reduce amount of data to download.
@wjt @barthalion what do you think?

**Comment by wjt** [comment]
That's probably fine – it does seem like it causes more trouble than it saves.

**Comment by barthalion** [comment]
Yeah, I don't think it's really needed.
