### ISSUE TITLE
Support updating <releases> in appdata

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#17]
Flathub now strongly encourages including release information in appdata; it is a hard requirement for PRs, and someday will be required for real builds, too. So this tool will have to learn to update that in cases where the appdata is not provided by upstream.

There are a number of ways we might determine the version number:

* Some packages include the version number in their URL (or are Debian packages with a structured version number)
* Some packages might have entries on release-monitoring.org which includes version information #16
* AppImages can be unpacked by passing `--appimage-extract`; the `.desktop` file within includes an `X-AppImage-Version` key

**Comment by wjt** [comment]
I implemented the `--appimage-extract` stuff on #18

**Comment by muelli** [comment]
for actually updating the XML file in place, something like

```
xmlstarlet ed --ps --inplace -L -s /component/releases -t elem -n releaseTMP -v "" \
    -i //releaseTMP -t attr -n "version" -v "20190801" \
    -i //releaseTMP -t attr -n "date" -v "2019-08-01" \
    -a //releaseTMP -t text -n text -v "description" \
    -r //releaseTMP -v release \
    *appdata.xml
```
might be handy.

**Comment by wjt** [comment]
I ended up writing my own bespoke in-place XML editor using Python's `xml.sax` API because I couldn't see a way to match indentation with `xmlstarlet`, and `xml.dom.minidom` can't preserve attribute ordering. Not my favourite activity but it passed the time on a delayed flight.

**Comment by muelli** [comment]
I was wondering whether we'd want a separate tool for adding a release to an appdata file.
Something like `appdata-add-release --description-from-file ./description   version  date` or so.
what do you think about that?

**Comment by wjt** [comment]
Such a tool sounds potentially useful for app maintainers, and I don't see why it couldn't live in this repo. I'm keen for the checker itself to be as non-interactive as possible – I think it is likely to be difficult to find a sufficiently-generic way to automatically add a description!
