### ISSUE TITLE
Changing branch for Flathub Bot pulls

### ISSUE THREAD

**Issue by EricKotato** [flathub-infra/flatpak-external-data-checker#171]
Currently in https://github.com/flathub/io.github.kotatogram Flathub Bot opens pull requests to `master` branch. Can I request to change it to `beta`? In Kotatogram stable version contains only stable version changes and beta contains both stable and beta changes, so that would be convenient.

Thanks in advance.

**Comment by gasinvein** [comment]
flatpak-external-data-checker can only handle the default branch currently (#75), so you may want to change the default branch from `master` to `beta` in the app repo. You can ask @barthalion or someone else with org-wide admin access to do this.

**Comment by EricKotato** [comment]
Will it affect branches on FlatHub? Stable Kotatogram currently can be installed from `flatpak install io.github.kotatogram`. If default branch will be beta, `flatpak install io.github.kotatogram` will still install from `master` or it will install from `beta`?

**Comment by gasinvein** [comment]
It will affect only git branches. Flathub builds flatpak `stable` branch from git `master` branch, and `beta` from `beta`, regardless of which one is git default.

**Comment by EricKotato** [comment]
Got it, thanks a lot.
