### ISSUE TITLE
Missing developer/project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [flathub-infra/flatpak-external-data-checker#177]
Hello. As noticeable the worth mentioning **developer/project/organisation** name is missing. It is then dully reported as "_Unknown_" when exhibited by Flatseal '`flatpak run com.github.tchx84.Flatseal`'. Mention regards to _Last updated:_ is probably expected to be exhibited as well.

![Flatpak_External_Data_Checker](https://user-images.githubusercontent.com/26058215/117962158-959b2000-b327-11eb-8c48-b806e6425550.png)

**Comment by Ricky-Tigg** [comment]
Interested?

**Comment by Ricky-Tigg** [comment]
E.g. | developer name's value is part of the application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name).

**Comment by wjt** [comment]
Patch very much welcome!

**Comment by Ricky-Tigg** [comment]
I wish i was a developer. Nevertheless Imanaged to figure out that relevant values are to be inserted into [org.flathub.flatpak-external-data-checker.metainfo.xml](https://github.com/flathub/flatpak-external-data-checker/blob/master/data/org.flathub.flatpak-external-data-checker.metainfo.xml).

**Comment by Ricky-Tigg** [comment]
I wish i was a developer. Nevertheless I managed to figure out that relevant values are to be inserted into [org.flathub.flatpak-external-data-checker.metainfo.xml](https://github.com/flathub/flatpak-external-data-checker/blob/master/data/org.flathub.flatpak-external-data-checker.metainfo.xml).

**Comment by Ricky-Tigg** [comment]
_Developer activity **null**_.

Task;
- **no** knowledge of code required
- **full instruction** for fix provided

Since that is at most a three minutes task, if that state of inactivity persists, the present ticket will be closed yet today.

**Comment by wjt** [comment]
Great, why not edit the file you linked to and send a pull request?

- Go to https://github.com/flathub/flatpak-external-data-checker/blob/master/data/org.flathub.flatpak-external-data-checker.metainfo.xml
- Click the pencil icon
- Add the relevant values
- Select "Create a new branch for this commit and start a pull request"
- Click *Propose changes*

Thanks!

**Comment by Ricky-Tigg** [comment]
Conventional addition would be as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="console-application">
  (...)
  <releases>
   <release version="version_number" date="YYYY-MM-DD" />
  </releases>
  <developer_name>FlatHub</developer_name>
</component>
```
Neverthelesss it looks like that present component lack  a release version number and release date. Is that event so? If so, the following addition would be useless.
```xml
  <releases>
   <release version="version_number" date="YYYY-MM-DD" />
  </releases>
```
