### ISSUE TITLE
rotating-urls checker adds information to url which is unneeded

### ISSUE THREAD

**Issue by lionirdeadman** [flathub-infra/flatpak-external-data-checker#179]
As seen on https://github.com/flathub/io.atom.Atom/pull/101 , it seems that f-e-d-c adds information to the end of the URL.

**Comment by gasinvein** [comment]
This is how rotating-url works - it tracks where the specified url (`https://atom.io/download/deb` in this case) redurects us to; currently it redirects to the URL you see in the PR. We have no way of knowing which url params are needed and which aren't.

**Comment by lionirdeadman** [comment]
Hmmm, could there be an option to remove parameters to avoid that? (since it's unneeded here)

**Comment by gasinvein** [comment]
These params are probably used only for tracking/counting unique downloads, but we can't just blindly drop all GET params, because there are URLs like `/download.php?file=payload.tar.gz` where the params are essential.

**Comment by gasinvein** [comment]
> Hmmm, could there be an option to remove parameters to avoid that? (since it's unneeded here)

Well, I think we can add such option (disabled by default).

**Comment by wjt** [comment]
It already unconditionally removes parameters beginning with `_` to deal with a similar issue with Zoom. We might be able to get away with stripping them all and seeing if anything breaks.

**Comment by gasinvein** [comment]
I'm pretty sure something will break if we just start to unconditionally remove _all_ GET params. Making this opt-in seems reasonable to me. Maybe even Zoom itself would opt-in? Are there any other apps that rely on this behavior?

**Comment by wjt** [comment]
As mentioned on #182, I don't expect removing all query parameters to have any effect (unless my analysis is buggy)

**Comment by lionirdeadman** [comment]
Maybe it should be opt-out then?
