### ISSUE TITLE
Supporting for semantic versioning (SemVer)

### ISSUE THREAD

**Issue by sophie-h** [flathub-infra/flatpak-external-data-checker#180]
In Pika Backup I use semantic versioning. I use Flathub beta channel and want the newest version (beta or release) to be deployed there. However "precedence" in semantic versioning has a twist: `1.0.0-alpha < 1.0.0` while usual sort algorithms come up with the exact opposite result. This means that currently flatpak-external-data-checker prefers 1.0.0-beta over the release version 1.0.0.

Maybe it would be possible to add a flag to enable semantic versioning?

**Comment by gasinvein** [comment]
Since the project is hosted on Gnome Gitlab, I'd suggest to use json checker against gitlab API instead to get the latest (chronologically) tag.
Try something like this:
```json
"x-checker-data": {
    "type": "json",
    "url": "https://gitlab.gnome.org/api/v4/projects/World%2Fpika-backup/repository/tags",
    "tag-query": "first | .name",
    "commit-query": "first | .commit.id",
    "timestamp-query": "first | .commit.committed_date",
    "version-query": "$tag | sub(\"^[vV]\"; \"\")"
}
```
or with releases endpoint:
```json
"x-checker-data": {
    "type": "json",
    "url": "https://gitlab.gnome.org/api/v4/projects/World%2Fpika-backup/releases",
    "tag-query": "first | .tag_name",
    "commit-query": "first | .commit.id",
    "timestamp-query": "first | .released_at",
    "version-query": "$tag | sub(\"^[vV]\"; \"\")"
}
```

**Comment by sophie-h** [comment]
I don't understand how this helps. There is no information about how the json checker determines precedence.

**Comment by gasinvein** [comment]
>how the json checker determines precedence

It doesn't, unless you use more complex query with custom sorting. The examples above just use the first tag/release that Gitlab API returns (AFAICT it always returns the latest one).

**Comment by sophie-h** [comment]
I might have the following order of releases

- 0.3.0
- 0.4.0-beta.1
- 0.3.1

So chronological order does not help.

**Comment by gasinvein** [comment]
Opened #181, it introduces `version-scheme` option for Git Checker metadata, that, if set to `semantic`, will use semantic version parser for sorting tags. Does it suffice for your case?
If you're familiar with podman/docker (or can use f-e-d-c on host), testing it would be helpful.

**Comment by sophie-h** [comment]
Sounds great! I will give it a try to figure out how to get this running.
