### ISSUE TITLE
Update runescape.deb to 2.2.9 #164 is the wrong size again

### ISSUE THREAD

**Issue by zomzol** [flathub-infra/flatpak-external-data-checker#191]
flatpak install flathub com.jagex.RuneScape
Looking for matches…

com.jagex.RuneScape permissions:
    ipc           network     pulseaudio     x11     devices
    tags [1]

    [1] proprietary

        ID                     Branch    Op    Remote     Download
 1. [✗] com.jagex.RuneScape    stable    i     flathub    3.9 MB / 13.5 MB

Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb
error: Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb
owner@owner-HP-Pavilion-g6-Notebook

**Comment by gasinvein** [comment]
As far as I understand, the upstream publishes new releases without bumping the .deb release, resulting in checksum/size change of the same url. I'm not sure if anything can be done about it but to update the flatpak more frequently, maybe even automatically.
