### ISSUE TITLE
Implicit automerge doesn't trigger for most checkers

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#193]
It used to work before. I suspect that it regressed after #119. More specifically, 1658c4190746b0adf44b8fc4daebc11caa827fef makes it so that if if an `extra-data` source has check method other than url, the data never reaches `URLChecker` and never gets `BROKEN` status, thus, the condition for implicit automerge is never met.
CC @Garbee

**Comment by Garbee** [comment]
Ah yea, that PR looks right. February 8th was the last successful auto-merge. Then on the 22nd I had to start manually merging them again.

**Comment by Garbee** [comment]
Since adding `"automerge-flathubbot-prs": true` to the `flathub.json` in the repo it is now auto-merging again. Only odd thing is now rather than it being like a 1 hour delay it is like 6 on the last one. I'll let the current one auto-merge and see how long it takes as well.

Could there just be a change in default behavior?

**Comment by gasinvein** [comment]
> now rather than it being like a 1 hour delay it is like 6 on the last one

This may happen if github CI status didn't change to "passed" after successful build. This happens from time to time, maybe some callback hangs or something.

**Comment by gasinvein** [comment]
@wjt What do you think, how should we fix this? I can think of several ways:
- Bring back the old behavior, i.e. always apply URLChecker; this seems wrong - it'll drop the new version if current one is invalid
- Require each checker to declare if the new version is a new release or a remote data change
- Upon receiving a new version from any checker, try to guess if this version is an actual new release, or just the current remote data has changed; set data state to BROKEN in case of the latter
