### ISSUE TITLE
Appdata not updated

### ISSUE THREAD

**Issue by cho2** [flathub-infra/flatpak-external-data-checker#197]
https://github.com/flathub/com.slack.Slack/issues/130

> On 4.15.0 (https://github.com/flathub/com.slack.Slack/pull/116/files), appdata still updated 

> On 4.16.0 (https://github.com/flathub/com.slack.Slack/pull/120/files) and 4.17.0 (https://github.com/flathub/com.slack.Slack/pull/121/files), appdata no longer updated.

> https://github.com/flathub/com.slack.Slack/issues/128#issuecomment-870463120
Although the latest version is 4.17.0, flatpak info still showing 4.15.0

**Comment by gasinvein** [comment]
This is likely because you've added pipewire module after Slack, which f-e-d-c assumes to be the actual app. Set `is-main-source` property to `true` in Slack module's `x-checker-data`.
