### ISSUE TITLE
Timezone location in HTTP `Date` header is unsupported

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#205]
E.g. `Fri, 17 Nov 2017 13:46:28 Asia/Shanghai` can't be parsed and raises `ValueError`. And seems like there is no way to parse timezone database location name with `datetime.datetime`.
Does anyone know a library suitable for parsing HTTP `Date` header?

**Comment by wjt** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date and other sources like https://httpwg.org/specs/rfc7231.html#header.date that header is illegal. In that format (`IMF-fixdate` in the language of RFC 7231) the zone field is the literal string `GMT`. So it may be hard to find an off-the-shelf parser for this illegal format. :-)

Where is this seen?

**Comment by gasinvein** [comment]
>Where is this seen?

We're getting it from [here](https://github.com/flathub/com.netease.CloudMusic/blob/535f296037ef6d72f5a1f189fca4a2797f1cea62/com.netease.CloudMusic.json#L93).
