### ISSUE TITLE
Raise custom exceptions on non-fatal errors

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#212]
...instead of returning None or just doing nothing in case of errors.

The exceptions can be catched and stored, allowing us to do 2 things:

- Alter program exit code depending on amount of collected errors when running in validation mode (#201)
- Report collected errors to user, by printing or including in Github PR comment (#130)

**Comment by gasinvein** [comment]
@wjt Do you have some thoughts on this?

**Comment by gasinvein** [comment]
While reworking checkers this way, I've realized we have some inconsistency in their behaviour: different checkers treat different situations as broken source. I guess it's about time to unify this.
The question is, in what case we should consider a source broken? Currently there are two very distinct cases, when a checker
1. has fetched new state for the same version and it doesn't match current state (e.g. checksum mismatch for the same URL)
2. failed to fetch new state (in this case we don't know anything about the current state)

Should we consider a source to be broken in case 1, 2 or both?

**Comment by wjt** [comment]
I think the most useful definition of broken is 'current manifest cannot be installed', which is 1. 2 is also interesting but is different and I think less serious.

**Comment by wjt** [comment]
> ...instead of returning None or just doing nothing in case of errors.

I think this is a good idea.
 
>     * Alter program exit code depending on amount of collected errors when running in validation mode ([Provide an option to only validate x-checker-data #201](https://github.com/flathub/flatpak-external-data-checker/issues/201))

Beware that the exit code may be an 'int' in python, but is actually a byte for the OS, and the given value is taken mod 256, so `exit(256)` is a successful exit. I learned this the hard way when a check which should have failed succeeded. I don't think the exit code should be based on the number of collected errors, except "zero" Vs "non-zero".

**Comment by gasinvein** [comment]
> definition of broken is 'current manifest cannot be installed'

I thought the same way, too, but then it further splits case 1 into two more different cases:

1. Source integrity has changed
2. Source is unavailable (e.g. HTTP 404)

Should we distinguish between these?
Also note that broken source means the manifest cannot be installed only in case of extra-data, but cannot be built in case of other source types.

> Beware that the exit code may be an 'int' in python, but is actually a byte for the OS, and the given value is taken mod 256, so `exit(256)` is a successful exit. I learned this the hard way when a check which should have failed succeeded.

Huh, I didn't know this either. Thanks for the tip.

**Comment by gasinvein** [comment]
@wjt Opened #213. It should largely retain current behaviour, except for non-validating checkers don't set broken status anymore when the can't get new version.
