### ISSUE TITLE
Jetbrains checker doesn't handle metainfo files

### ISSUE THREAD

**Issue by FakeShemp** [flathub-infra/flatpak-external-data-checker#233]
I just noticed that the Jetbrains checker wasn't updating my metainfo files, but it seem to work with appdata files. Perhaps it needs something tweaked.

See https://github.com/flathub/com.jetbrains.Rider/pull/31 for an example.

**Comment by gasinvein** [comment]
I guess this happens because the main upstream source isn't the last one. Try adding `is-main-source: true` to `x-checher-data` on the app source.

**Comment by FakeShemp** [comment]
Yes, this works. Thanks.
