### ISSUE TITLE
Builds fail to push to ghcr.io

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#234]
e.g. https://github.com/flathub/flatpak-external-data-checker/runs/3663245303?check_suite_focus=true

```
Run docker image tag \
  docker image tag \
    flathub/flatpak-external-data-checker:build \
    ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${GITHUB_SHA::7}
  docker image tag \
    flathub/flatpak-external-data-checker:build \
    ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
  docker image push --all-tags \
    ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
  shell: /usr/bin/bash -e {0}
  env:
    DOCKER_REGISTRY: ghcr.io
    DOCKER_IMAGE: flathub/flatpak-external-data-checker
The push refers to repository [ghcr.io/flathub/flatpak-external-data-checker]
f1d3cf9dd85c: Preparing
dfb704943771: Preparing
394b18103952: Preparing
f08810f3cd8d: Preparing
338e3bdb6470: Preparing
7e41d8465083: Preparing
d0c00edbf9f0: Preparing
799760671c38: Preparing
7e41d8465083: Waiting
d0c00edbf9f0: Waiting
799760671c38: Waiting
denied: permission_denied: write_package
Error: Process completed with exit code 1.
```

Looks like a regression from 20277aa905a479aea50f5b1c496dae799bd58ded ?

**Comment by wjt** [comment]
@gasinvein what was the context of the change in 20277aa?

**Comment by gasinvein** [comment]
> Looks like a regression from [20277aa](https://github.com/flathub/flatpak-external-data-checker/commit/20277aa905a479aea50f5b1c496dae799bd58ded) ?

Well, it did work previously. I wonder what's different since then?

> what was the context of the change in [20277aa](https://github.com/flathub/flatpak-external-data-checker/commit/20277aa905a479aea50f5b1c496dae799bd58ded)?

Initially GHCR didn't allow authentication using `GITHUB_TOKEN`. Now it does, so we decided to switch flathub docker images to that, since it's safer than PATs (that were used previously).

**Comment by wjt** [comment]
The only changes in the repo since then are merging #221 #230 #231. 

I don't think that any of those changes landed on master until today. 

If you look at the build log for 20277aa https://github.com/flathub/flatpak-external-data-checker/runs/3585711176 and expand "Push image to registry", I don't think there was anything to push. All layers there had "Layer already exists". So the fact that the token apparently can't write to the registry was perhaps a non-issue.

**Comment by gasinvein** [comment]
> expand "Push image to registry", I don't think there was anything to push

Interesting. Maybe `GITHUB_TOKEN` behaves somehow differently for org-owned repositories? Pushing to ghcr.io with `GITHUB_TOKEN` did work in my accounts' Wine flatpak repo.

**Comment by dbnicholson** [comment]
> > expand "Push image to registry", I don't think there was anything to push
> 
> Interesting. Maybe `GITHUB_TOKEN` behaves somehow differently for org-owned repositories? Pushing to ghcr.io with `GITHUB_TOKEN` did work in my accounts' Wine flatpak repo.

There are a couple layers to what a GitHub App (as represented by `GITHUB_TOKEN`) has permissions to do.

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#how-the-permissions-are-calculated-for-a-workflow-job
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action

In particular, you need `contents: read` and `packages: write`, and I think best practice would be to specify those in the workflow so you're not relying on the repo or org defaults.

**Comment by gasinvein** [comment]
@dbnicholson Thanks, but setting permissions explicitly didn't help. I suspect it may have something to do with github package settings - a package can restrict who and from what repos can push it. Sadly I don't have access to the package settings to verify.

**Comment by gasinvein** [comment]
Fixed by granting this git repo write perms to the package in the package settings.
