### ISSUE TITLE
Got a PR that doesn't make sense

### ISSUE THREAD

**Issue by WhyNotHugo** [flathub-infra/flatpak-external-data-checker#238]
I got this PR which doesn't make sense:

https://github.com/flathub/rest.insomnia.Insomnia/pull/13/files

It just "updates" to the same version. It also generated an invalid XML, since the same release got duplicated.

**Comment by gasinvein** [comment]
Looks like regression after 78ae6b070cc35e9a1da6979b4b6686e77a06f967: unparsing parsed URL can produce a different string if the original url contains redundant escaping (`@` escaped as `%40` in this case). This results in the new version erroneously mismatching the current one.

**Comment by WhyNotHugo** [comment]
Thanks!
