### ISSUE TITLE
Investigate Strange Downgrades 

### ISSUE THREAD

**Issue by rany2** [flathub-infra/flatpak-external-data-checker#254]
Flathub Bot has been downgrading Brave for a while now...

https://github.com/flathub/com.brave.Browser/pull/92
https://github.com/flathub/com.brave.Browser/pull/87

**Comment by gasinvein** [comment]
The url you use to track upstream versions has only one version, so it can't be sorting issue. I can only guess that upstream has accidentally put an older version there.

**Comment by wjt** [comment]
Based on https://github.com/flathub/com.brave.Browser/pulls?q=is%3Apr+is%3Aclosed and the commit history https://github.com/flathub/com.brave.Browser/commits/beta this appears to be increasing now.
