### ISSUE TITLE
Tabs in Flatpak manifests are converted to spaces

### ISSUE THREAD

**Issue by Newbytee** [flathub-infra/flatpak-external-data-checker#256]
As can be seen in this diff, tabs are for some reason converted to spaces by f-e-d-c when it issues an upgrade: https://github.com/flathub/com.jpexs.decompiler.flash/pull/9/files

I prefer to use tabs over spaces for various reasons. Is this a deliberate feature or something that could be fixed?

**Comment by wjt** [comment]
It is because I could not find a JSON implementation which preserves whitespace.

You could probably fix this specific case by having it detect the indentation in use in the source file when reading it, and then explicitly using the same indentation when writing. Interested in writing a patch?

**Comment by gasinvein** [comment]
> I could not find a JSON implementation which preserves whitespace.

Even if we find one, we'll still lose formatting, because we use json-glib to load and dump string before passing it to python library.
