### ISSUE TITLE
Re-downloading static URLs is unnecessary

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#257]
We always download upstream file, even if it's not new, i.e. URL was unchanged. This is likely unnecessary in most cases and just wastes network bandwidth. Cases when supposedly the same URL gives changed data are rare and indicate something broken upstream, if this happens - the user may want to manually investigate the problem instead of receiving a PR with checksum update.
So, we should probably skip upstream file download when the URL stayed the same.

**Comment by tinywrkb** [comment]
This would be nice to have. Currently, the TexLive SDK extension has f-e-d-c property disabled for a source due to its size. I thought it's not acceptable to download over 3GB from the TexLive mirror on each f-e-d-c run.
