### ISSUE TITLE
YAML checker

### ISSUE THREAD

**Issue by d-513** [flathub-infra/flatpak-external-data-checker#268]
need to construct url using a yml file provided by upstream

**Comment by gasinvein** [comment]
Any example of such upstream yaml url?

**Comment by d-513** [comment]
From [#2784](https://github.com/flathub/flathub/pull/2784) -  site uses https://launcherupdates.lunarclientcdn.com/latest-linux.yml to get filename with version


> @gasinvein Any example of such upstream yaml url?

**Comment by d-513** [comment]
it seems to be a general appimage file with the yml. BalenaEtcher has it too https://github.com/balena-io/etcher/releases/ has latest-linux file

**Comment by gasinvein** [comment]
Interesting. Is this yaml file a manifest for some appimage self-update mechanism?

**Comment by d-513** [comment]
No idea, but may be it

**Comment by d-513** [comment]
Seems to be generated by https://github.com/electron-userland/electron-builder
