### ISSUE TITLE
PyPI checker wants to use Windows wheels

### ISSUE THREAD

**Issue by JakobDev** [flathub-infra/flatpak-external-data-checker#277]
I added x-cheker-data to my Python modules yesterday, as it is now supported by flatpak-pip-generator. Today I got a [a PR from Flathubbot](https://github.com/flathub/com.gitlab.JakobDev.jdTextEdit/pull/1) who wants to use the Windows Wheels of Pyenchant (on a Linux System). Pyenchant has the exact same version. It just wanna change the wheels used.

**Comment by gasinvein** [comment]
Hmm, I thought only noarch wheels can have `python_version` values `py3` and `py2.py3` in PyPI API, since otherwise wheels would have ABI tied to python version. Apparently I was wrong, we'll need additional filtering.
