### ISSUE TITLE
Wants to change the checksum (which is wrong)

### ISSUE THREAD

**Issue by gerlachs** [flathub-infra/flatpak-external-data-checker#279]
https://github.com/flathub/org.kde.labplot2/pull/7/files

correct checksum:
  -                 "sha256": "b367c695d2831958e7166921c3b356d5dfa51b1ecee505b97416ba39d1b6c17a",
wrong checksum:
  +                "sha256": "748994dd1c819b88567e3539ea1f0ec2dd39fc0ed2884c033afa3da66efb5f4e",

**Comment by wjt** [comment]
The second checksum is the uncompressed file.

```
wjt@toolbox:~☭ curl --location --silent http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-4.1.0.tar.gz | gunzip | sha256sum -
748994dd1c819b88567e3539ea1f0ec2dd39fc0ed2884c033afa3da66efb5f4e  -
```

```
wjt@toolbox:~☭  curl --location --silent --head http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-4.1.0.tar.gz 
HTTP/1.0 301 Moved Permanently
Location: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-4.1.0.tar.gz
Server: BigIP
Connection: Keep-Alive
Content-Length: 0

HTTP/1.1 200 OK
Date: Wed, 23 Mar 2022 10:28:20 GMT
Server: WebServer/1.0
X-Frame-Options: sameorigin
Last-Modified: Tue, 15 Mar 2022 18:22:51 GMT
ETag: "417a8f8-41b120-5da45e283d697"
Accept-Ranges: bytes
Content-Length: 4305184
Content-Security-Policy: frame-ancestors 'self' cms.nasa.gov www.nasa.gov;
Connection: close
Content-Type: application/x-tar
Content-Encoding: x-gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Security-Policy: upgrade-insecure-requests
```

**Comment by wjt** [comment]
I think it is because:
```
Content-Type: application/x-tar
Content-Encoding: x-gzip
```

rather than:

```
Content-Type: application/x-compressed-tar
```

**Comment by gasinvein** [comment]
Looks like another http compression issue, similar to #159
Update: @wjt if I understood correctly what happens here, if the clients sends `Accept-Encoding: gzip`, then the server responds with `Content-Encoding: gzip`, thus the `.tar.gz` files gets decompressed on the fly. The correct checksum is for the `.tar.gz`, while the incorrect one is for the `.tar`.

**Comment by wjt** [comment]
I feel like we will forever be chasing bugs of this nature unless we change fedc to use the same codepaths that Flatpak uses to download files. But unfortunately based on a quick skim, Flatpak's HTTP functions are private, and flatpak-builder has what looks suspiciously like a copy-paste of them.

**Comment by gasinvein** [comment]
Does flatpak (or libsoup by default) send `Accept-Encoding` request header? If it doesn't, I guess we should stop sending it, too. It probably won't rule out all bugs like this, but at least it could bring f-e-d-c http client behaviour closer to what flatpak does.
