### ISSUE TITLE
Add check for artifacts from Github releases

### ISSUE THREAD

**Issue by darkdragon-001** [flathub-infra/flatpak-external-data-checker#293]
Github releases have a clear URI scheme: `https://github.com/ORG/PROJECT/releases/download/TAG/FILE`. So the checker just needs to get all releases via [API](https://docs.github.com/en/rest/releases/releases#list-releases) and use the same logic like comparing git tags in order to find out the latest release.

**Comment by gasinvein** [comment]
You can use [JSON Checker](https://github.com/flathub/flatpak-external-data-checker#json-checker) with GitHub REST API; it's quite common practice, so you can find some examples on Flathub.
