### ISSUE TITLE
Flathubbot starting test build on merged PR

### ISSUE THREAD

**Issue by JakobDev** [flathub-infra/flatpak-external-data-checker#300]
The flathubbot created a [PR to update 2 Python modules](https://github.com/flathub/com.gitlab.JakobDev.jdMinecraftLauncher/pull/4). I was online at this time, so I merged it directly. A few minutes later a test build stared on the merged PR. I think this should not happen.

**Comment by vchernin** [comment]
Isn't the logic for flathubbot builds somewhere outside f-e-d-c? In any case, I agree flathubbot should avoid builds on deleted/merged branches.

**Comment by wjt** [comment]
Yep, nothing to do with this repo.

**Comment by JakobDev** [comment]
On which repo should I open the Issue?

**Comment by wjt** [comment]
I didn't know either. So, I [searched the Flathub org for "queued test build"](https://github.com/search?q=org%3Aflathub+%22Queued+test+build%22&type=code) and the lone result is https://github.com/flathub/buildbot/blob/14375f31b3b3bf5cba943f157b1d8af9ba448c8e/master/buildbot/flathub_master.py so I suggest that repo.
