### ISSUE TITLE
htmlchecker: Support versions

### ISSUE THREAD

**Issue by tinywrkb** [flathub-infra/flatpak-external-data-checker#309]
Example module:

`python-apsw.yaml`

```
name: python-apsw
buildsystem: simple
build-commands:
  - python setup.py build --enable=load_extension
  - python setup.py install --skip-build --prefix=/app --root=/ --optimize=1
post-install:
  # run tests as the application might not check if apsw import is failing and can possibly overwrite the db
  - gcc ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -fPIC -shared -o testextension.sqlext src/testextension.c
  - python setup.py test
sources:
  - type: archive
    url: https://github.com/rogerbinns/apsw/releases/download/3.36.0-r1/apsw-3.36.0-r1.zip
    sha256: 17355c39a8cdb9b9cd75b76d883b624c0dd05f80a6677c693b67c343c2381871
    x-checker-data:
      type: html
      url: https://github.com/rogerbinns/apsw/tags.atom
      version-pattern: <title>([\d.]*)-r\d</title>
      # NOTE: version must match runtime's libsqlite3.so
      versions:
        '<': 3.38.0
      url-template: https://github.com/rogerbinns/apsw/releases/download/${version}-r1/apsw-${version}-r1.zip
```

Without `versions` support, a workaround is needed.
```
version-pattern: <title>(3.36[\d.]*)-r\d</title>
```

**Comment by gasinvein** [comment]
This particular example is rather strange, why would one even use regexps against GH atom feed when there is a proper API that can be interacted with JSONChecker?
But anyway, I guess such feature can be useful in some cases.

**Comment by tinywrkb** [comment]
At least for private and WIP packaging, I try to avoid the JSON checker in non-primary modules due to GH's rate limit for unauthenticated queries.  
Also, didn't remember if we have version sorting support in the JSON checker, so I just used the HTML checker.

**Comment by gasinvein** [comment]
> didn't remember if we have version sorting support in the JSON checker

We don't have it on f-e-d-c side, but it's doable on jq side with expressions like `sort_by(.tag_name | split(".") | map(tonumber))` (this one is oversimplified and won't suffice for most real-world scenarios, but you get the idea).

**Comment by gasinvein** [comment]
@wjt In order to properly support version filtering for HTMLChecker, we need to get a  version number associated with each URL. I'm afraid it's not possible when we get urls and versions independently, i.e. when `url-pattern` and `version-pattern` are both set and matched multiple items. This scenario is inherently broken and we should've never supported it in the first place, but now it seem like some people rely on it. What do you think, can we just invalidate it? Or we need some deprecation plan?
**Update**: Actually, it appears that only 5 apps use `url-pattern`. I guess I can fix them manually if we drop `url-pattern` support.

**Comment by wjt** [comment]
In this case it sounds like just fixing them will work. But I do wonder about the increasing "API" surface area in general, particularly when there is not AFAIK a good way to be notified about the checker failing on one of your repos

**Comment by gasinvein** [comment]
> there is not AFAIK a good way to be notified about the checker failing on one of your repos

I hope this problem will be gone when/if we switch from the "hosted" org-wide f-e-d-c workflow to per-repo GH workflow - failed action is visible to repo collaborators.
