### ISSUE TITLE
Jetbrains checker doesn't seem to be working

### ISSUE THREAD

**Issue by patriziobruno** [flathub-infra/flatpak-external-data-checker#324]
https://github.com/flathub/com.jetbrains.GoLand/blob/master/com.jetbrains.GoLand.yaml has been using the Jetbrains checker for a long while and has always worked, but the latest GoLang version is not picked up.

I ran flatpak-checker using latest flatpak from flathub and it works, maybe it's something related with flathub infra?

**Comment by gasinvein** [comment]
What do you expect it to do what it doesn't? Is there an update it doesn't detect?

**Comment by patriziobruno** [comment]
> What do you expect it to do what it doesn't? Is there an update it doesn't detect?

Yes, precisely. I ran it locally and it works. But it stopped working in flathub

**Comment by gasinvein** [comment]
Strange, it doesn't show me an update available for the current master branch of `com.jetbrains.GoLand`. Are you saying f-e-d-c says to you there is an update?

**Comment by patriziobruno** [comment]
My bad, I definitely had a problem on my machine and I missed it.
