### ISSUE TITLE
Support updating to latest Git tag matching some pattern

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#33]
Vim's development model is that each commit to the master branch gets a tag, and this is the only way to get fixes since the first release on the stable branch. As a result, the Flatpak builds from a Git tag.

https://github.com/flathub/org.vim.Vim/blob/master/auto-update.py implements logic to update to the HEAD of master and open a PR. It could be combined with this checker.

However – the current cronjob for that script only runs it weekly, to avoid update churn for users and PR spam for me. Perhaps the checker could have some heuristic to reduce the number of PRs generated.

**Comment by nanonyme** [comment]
We more or less have Git tracking available at https://gitlab.com/BuildStream/bst-external/blob/master/bst_external/sources/git_tag.py#L350-387

I was talking a bit about this on IRC, I think the same logic should be replicated here. Our approach supports majority of opensource projects using Git. I can take a look at this later if I have time. This is a non-trivial task if this should be implemented in a way that supports eg Gnome projects.

**Comment by bilelmoussaoui** [comment]
> We more or less have Git tracking available at https://gitlab.com/BuildStream/bst-external/blob/master/bst_external/sources/git_tag.py#L350-387
> 
> I was talking a bit about this on IRC, I think the same logic should be replicated here. Our approach supports majority of opensource projects using Git. I can take a look at this later if I have time. This is a non-trivial task if this should be implemented in a way that supports eg Gnome projects.

I think for gnome projects we should provide a different checker that would use download.gnome.org instead and properly handle the stable/unstable releases.

**Comment by nanonyme** [comment]
@bilelmoussaoui git_tag include/exclude can be used to configure stable/unstable updates like Gnome does.

**Comment by nanonyme** [comment]
But sure, for Gnome one usually uses tarballs still.

**Comment by gasinvein** [comment]
Work in progress, review/testing welcome #104

**Comment by gasinvein** [comment]
#115 implements this feature.
