### ISSUE TITLE
Unable to update AppStream metadata for JetBrains IntelliJ IDEA Ultimate edition

### ISSUE THREAD

**Issue by x80486** [flathub-infra/flatpak-external-data-checker#336]
`IntelliJ IDEA` uses the "external-data-checker" for automatic updates. This works fine for the `Community` edition, but somehow the `Ultimate` edition is unable to correctly update the AppStream metadata.

Is this a bug on for this piece of software? The only difference between these two Flatpaks is that the `Ultimate` edition is using the `extra-data` type, instead of `file`. I think that's what making the difference, but I don't know how that impacts the update.

**Comment by gasinvein** [comment]
> the `Ultimate` edition is unable to correctly update the AppStream metadata.

Please elaborate, what and how exactly is incorrect.

**Comment by gasinvein** [comment]
After a quick look over the app update PRs, I guess the problem is that appdata isn't updated at all. Try adding `is-main-source: true` to `x-checker-data` on the app source.

**Comment by x80486** [comment]
Here [is](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/pull/112/commits) is the last (automatic) pull request for `IntelliJ IDEA Community` — one commit, all required files updated, including AppStream metadata[.

Here [is](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/pull/112/commits](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/pull/120/commits)) is the last (automatic) pull request for `IntelliJ IDEA Ultimate` — two commits, last one made by myself because `.metainfo.xml` didn't get updated.

**Comment by x80486** [comment]
OK, I added it. Will check if it behaves correctly on the next upgrade — but I guess you know it will.

Do you know by any chances why the `Community` edition doesn't need this? Or should I added to it as well?

**Comment by gasinvein** [comment]
> Do you know by any chances why the `Community` edition doesn't need this? Or should I added to it as well?

Most likely because of the order of sources: in the `Community` app flatpak manifest the main app source is the last, while in the `Ultimate` one there is another remote source after the app source. When `is-main-source` isn't set anywhere, f-e-d-c assumes the last source to be the main one.
