### ISSUE TITLE
f-e-d-c crashes on updating AppStream

### ISSUE THREAD

**Issue by JakobDev** [flathub-infra/flatpak-external-data-checker#346]
f-e-d-c currently crashes on updating the [6.4 branch of com.riverbankcomputing.PyQt.BaseApp](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/tree/branch/6.4). 

```
INFO    src.manifest: Updating /github/workspace/pyqt/../pyqt-builder/pyqt-builder.json
INFO    src.manifest: Updating /github/workspace/pyqt/../pyqt-sip/pyqt-sip.json
INFO    src.manifest: Updating /github/workspace/pyqt/pyqt.json
INFO    src.manifest: Preparing to update appdata /github/workspace/com.riverbankcomputing.PyQt.BaseApp.metainfo.xml
Traceback (most recent call last):
  File "/app/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/src/main.py", line 457, in main
    outdated_num, errors_num, updated = asyncio.run(run_with_args(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/src/main.py", line 425, in run_with_args
    changes = manifest_checker.update_manifests()
  File "/app/src/manifest.py", line 546, in update_manifests
    self._update_appdata()
  File "/app/src/manifest.py", line 492, in _update_appdata
    assert selected_data is not None
AssertionError
```

The full log can be found in the [Action](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/actions/runs/4041799929/jobs/6948751257).

**Comment by gasinvein** [comment]
I guess this happens because the last module (`polish`) doesn't have any external sources, thus f-e-d-c can't associate its appdata with any version.

**Comment by JakobDev** [comment]
I will try to add `is-main-source` to the correct module to fix this. But I think f-e-d-c should show a correct error message with a hint to `is-main-source` in such a case.

**Comment by JakobDev** [comment]
I can confirm that this has fixed the Issue, so f-e-d-c just needs to implement a proper error message
