### ISSUE TITLE
Unwanted downgrade

### ISSUE THREAD

**Issue by ferraridamiano** [flathub-infra/flatpak-external-data-checker#348]
Hello, few weeks ago I added x-checker-data to the manifest of [my app on flathub](https://github.com/flathub/io.github.ferraridamiano.ConverterNOW). I did not update the app in the last few months and today I received an unwanted downgrade from flathub bot ([see this PR](https://github.com/flathub/io.github.ferraridamiano.ConverterNOW/pull/8)). If I run x-checker-data to my current repository nothing happens  because it is already updated (work as expected). What's wrong?

**Comment by gasinvein** [comment]
It's a bug that triggers occasionally, and seem like exclusively on GitHub. I couldn't reproduce it locally and don't know exactly why it happens.

**Comment by gasinvein** [comment]
Duplicate of #286
