### ISSUE TITLE
Incorrect downgrade of rest.

### ISSUE THREAD

**Issue by hfiguiere** [flathub-infra/flatpak-external-data-checker#358]
From this PR f-e-d-c want to downgrade rest

https://github.com/flathub/org.gnome.Photos/pull/46

However I can't figure out why not why was it just triggered. But 0.8.1 is definitely not more recent than 0.9.1, neither in date nor in order.

**Comment by ManuelHu** [comment]
see #338

**Comment by hfiguiere** [comment]
The thing is that while https://github.com/flathub/org.gnome.Photos/pull/44 did also try, the later PR https://github.com/flathub/org.gnome.Photos/pull/45 didn't. So it's not even consistent.

**Comment by Chocobo1** [comment]
Same incorrect downgrade here: https://github.com/flathub/org.qbittorrent.qBittorrent/pull/130
