### ISSUE TITLE
Using mirror-urls when checking tags

### ISSUE THREAD

**Issue by kevinlekiller** [flathub-infra/flatpak-external-data-checker#364]
As seen here : https://github.com/flathub/io.mpv.Mpv/pull/184

The build failed because the checker only looked at the url, not the mirror-urls:

https://github.com/flathub/io.mpv.Mpv/blob/9f8c304f2d89ed96be8641f4a155e3f4f6bd6530/io.mpv.Mpv.yml#L120-L128

    ...
    ERROR   src.manifest: Failed to check git uchardet/uchardet.git with GitChecker: Listing Git remote failed: Command '['git', 'ls-remote', '--exit-code', 'https://github.com/freedesktop/uchardet.git']' returned non-zero exit status 128.
    ...
    WARNING src.main: Check finished with 1 error(s)
    program finished with exit code 1

**Comment by gasinvein** [comment]
Huh, I didn't know flatpak-builder supports `mirror-urls` for Git sources.

**Comment by kevinlekiller** [comment]
You're right, I just checked the manual, it's only for archives, odd it doesn't throw a warning!

I'll close this issue then.

Thanks.
