### ISSUE TITLE
Instructions to install from PR do not work

### ISSUE THREAD

**Issue by Maltimore** [flathub-infra/flatpak-external-data-checker#368]
In the following PR: https://github.com/flathub/us.zoom.Zoom/pull/386#issuecomment-1536087664

I tried to follow the instructions to install

```
flatpak install --user https://dl.flathub.org/build-repo/21955/us.zoom.Zoom.flatpakref
```

But got the error

```
error: Can't load uri https://dl.flathub.org/build-repo/21955/us.zoom.Zoom.flatpakref: Server returned status 404: Not Found
```

**Comment by wjt** [comment]
Those builds are actually made by a different component. Anyway, they expire after a few days.

**Comment by Maltimore** [comment]
Understood, thanks :)
Could you point me to the repo of the component that makes these builds? Because the first comment of the PR (the comment of the bot) says to open an issue here.

**Comment by wjt** [comment]
That's about an issue with the PR itself.

The 404 is just because the test build expired. There is no bug to report. A committer to the `us.zoom.Zoom` repo, or a Flathub admin, needs to comment `bot, build` to trigger a rebuild.
