### ISSUE TITLE
Timezone in last-modified HTTP header breaks urlchecker

### ISSUE THREAD

**Issue by bbhtt** [flathub-infra/flatpak-external-data-checker#370]
Example http://d1.music.126.net/dmusic/netease-cloud-music_1.2.1_amd64_ubuntu_20190428.deb
 
gives the header `last-modified Mon, 29 Apr 2019 10:43:55 Asia/Shanghai`

So urlchecker fails `URLChecker: Cannot parse date/time: Mon, 29 Apr 2019 10:43:55 Asia/Shanghai`

Affected application: https://github.com/flathub/com.netease.CloudMusic/pull/7

**Comment by bbhtt** [comment]
I think to solve this either external-data-checker should allow skipping the check for `extra-data` (disabling it via flathub.json has no effect) or use workarounds to deal with invalid headers

**Comment by wjt** [comment]
Dupe of #205

**Comment by bbhtt** [comment]
Thanks, closing
