### ISSUE TITLE
Runtime update checker

### ISSUE THREAD

**Issue by razzeee** [flathub-infra/flatpak-external-data-checker#375]
Would be cool, if this would be able to check the runtimes and suggest updating them.

- Check which runtime an app uses
- If there is a newer runtime, send a PR with that runtime

**Comment by razzeee** [comment]
See https://github.com/flathub/flathub/issues/887

**Comment by bbhtt** [comment]
I think this falls within the scope of https://github.com/flathub/flatpak-external-data-checker/issues/161

**Comment by razzeee** [comment]
Closing in favor of that
