### ISSUE TITLE
Add emojis to build results in GitHub MRs

### ISSUE THREAD

**Issue by Justinzobel** [flathub-infra/flatpak-external-data-checker#376]
:green_circle: for success
:red_circle:  for failure

**Comment by wjt** [comment]
I can't transfer this issue to the correct repo. Here is the function you could send a patch to:

https://github.com/flathub/buildbot/blob/79ab5dc8f142a9cce29e7bb4fd1bbab2e98be9a0/master/buildbot/flathub_master.py#L1411-L1433

**Comment by Justinzobel** [comment]
If I knew how to write and validate python, sure, but I do not.

**Comment by wjt** [comment]
No time like the present to learn!

**Comment by Justinzobel** [comment]
Just the first two words apply. Already got a plate full of many other things.
