### ISSUE TITLE
Add a command to recheck for updates

### ISSUE THREAD

**Issue by adil192** [flathub-infra/flatpak-external-data-checker#379]
## Motivation

In my app [Ricochlime](https://github.com/adil192/ricochlime), I build two binaries for `amd64` and `x86_64`.

The `amd64` is built more slowly than the `x86_64` binary, so when the bot picks up an update and submits a PR, only the `x86_64` binary is updated to the latest tag while the `amd64` binary is still building. Ideally, they'd both be updated in the same PR.

E.g. This PR only updates `Ricochlime_v0.5.1_Linux_x86_64.tar.gz` and not `Ricochlime_v0.5.1_Linux_arm64.tar.gz`, since `Ricochlime_v0.5.1_Linux_arm64.tar.gz` wasn't finished building yet.

![A PR that only updates one binary and not the other](https://github.com/flathub/flatpak-external-data-checker/assets/21128619/68db04d9-6bbd-4428-b30e-d14b9e2237ee)

Currently, I just have to close the PR and wait for the bot to submit another PR in its next run (an hour later?).

<img src="https://github.com/flathub/flatpak-external-data-checker/assets/21128619/c3ff90bd-e08c-452b-9675-6ed42378279a" alt="A list of pull requests where every second PR only updates one of the two binaries" width=500>

## Proposal

On a PR that only updates one file and not the other, the developer can comment something like this to recheck for updates and update the PR:
```
bot, check for updates
```

**Comment by bbhtt** [comment]
This isn't related to x-checker. The x-checker runs every hour on flathub infra, if the update to your app wasn't available when it was started it won't pull it. You can run it locally multiple times to pull as many updates you want.

Eg. https://github.com/flathub/com.adilhanney.ricochlime/pull/12 updated both when the other one failed https://github.com/flathub/com.adilhanney.ricochlime/pull/11

The buildbot is separate from x-checker.

I'd suggest defining your own workflow and schedule separate from flathub https://github.com/flathub/com.brave.Browser/blob/3db27f57ed17a7d8b00e0386fa857348ca1e289b/.github/workflows/update.yaml#L4C1-L4C27.

**Comment by wjt** [comment]
If it is consistently the arm64 source that arrives later, you could cheat by marking the arm64 source as the main source.  (The downside would be that you would never get a PR for a release that revs the x86-64 source but not the arm64 one.)
