### ISSUE TITLE
Same version duplicated PRs on Slack flathub

### ISSUE THREAD

**Issue by bhack** [flathub-infra/flatpak-external-data-checker#381]
https://github.com/flathub/com.slack.Slack/pull/214
https://github.com/flathub/com.slack.Slack/pull/216

**Comment by vchernin** [comment]
This is because of the branch name, see https://github.com/flathub/flatpak-external-data-checker/issues/62 and https://github.com/flathub/flatpak-external-data-checker/issues/289

**Comment by bhack** [comment]
ok
