### ISSUE TITLE
`"is-main-source": false` is treated as main source

### ISSUE THREAD

**Issue by adil192** [flathub-infra/flatpak-external-data-checker#398]
In https://github.com/flathub/com.adilhanney.saber/pull/100, I set `is-main-source` to false for the x86_64 source (following https://github.com/flathub/flatpak-external-data-checker/issues/379#issuecomment-1806862390).

But https://github.com/flathub/com.adilhanney.saber/pull/101 created a pull request for just the x86_64 source.

I'm guessing this is because `is-main-source` is present even though it is false. 

![Commit from flathubbot that only updates the x86_64 source](https://github.com/flathub/flatpak-external-data-checker/assets/21128619/6a96819a-df3d-495b-adac-3371a950d2dd)

**Comment by wjt** [comment]
> To only open PRs when at least one important source is updated, first set `require-important-update` to `true` in `flathub.json`.

- https://github.com/flathub/flatpak-external-data-checker#selectively-submitting-prs
