### ISSUE TITLE
Automatic merging doesn't work

### ISSUE THREAD

**Issue by FakeShemp** [flathub-infra/flatpak-external-data-checker#399]
Since about two weeks ago, automatic merging of commits with broken extra data urls seems to be not work.

Example of issue: https://github.com/flathub/com.hamrick.VueScan/pull/1204

This is how it usually goes: https://github.com/flathub/com.hamrick.VueScan/pull/1203

**Comment by wjt** [comment]
I found an action run when a PR was already open & had not yet been merged.

https://github.com/flathub/flathub/actions/runs/6994640746/job/19028637926#step:3:9948

https://gist.github.com/wjt/9dbef0e96aa54136cf882df06e4dccf6

Not sure why it is not flagging the current URLs as broken which is what previously triggered the automerge.

**Comment by hfiguiere** [comment]
@barthalion looks like an infra problem

**Comment by barthalion** [comment]
Seems to be transient, given VueScan has been successfully merged since then. Nothing to do here, I guess?
