### ISSUE TITLE
Jellyfin on TV needs server version 10.9

### ISSUE THREAD

**Issue by gopikrishnansa** [flathub-infra/flatpak-external-data-checker#432]
Jellyfin on TV needs server version 10.9. please update it on flathub

**Comment by wjt** [comment]
https://github.com/flathub/org.jellyfin.JellyfinServer/issues/282

**Comment by wjt** [comment]
This project's maintainers are not responsible for keeping apps up to date: this is a tool to help app maintainers do that.
