### ISSUE TITLE
Clearly state implications of module updates

### ISSUE THREAD

**Issue by hknaack** [flathub-infra/flatpak-external-data-checker#437]
I saw this PR by flathubbot: https://github.com/flathub/org.wireshark.Wireshark/pull/200#issue-2503367315

Having the liblzma-problem from Easter this year in mind, I was wondering if such a problem of manipulated archives on the download server is in any way addressed by this project. My quick review of the source code did not show any indication of awareness of such source code manipulation problems (but my Python skills may be too poor, either).

So, I would like to know, if updated module source code archives are validated against something like the Git-Repository they originate from.
If such validation is not performed, I think the automatically generated PR or commit message should state, that the updated source code has not been validated and it is the responsibility of the person merging the PR to do such validation.

**Comment by wjt** [comment]
I think that's implicit. The maintainer should always validate the update, just as they should test it.
