### ISSUE TITLE
Modules which are a string should also be parsed

### ISSUE THREAD

**Issue by ahayzen** [flathub-infra/flatpak-external-data-checker#7]
Modules which are a string also need to be parsed, as they may contain extra-data or need CVE checking etc. (these pulls skip the string at the moment https://github.com/joaquimrocha/flatpak-external-data-checker/pull/3 https://github.com/joaquimrocha/flatpak-external-data-checker/pull/6)

The string is just a patch to a nested file, so we should be able to iterate through them. 
Eg
```
"modules": [
    "shared-modules/udev/udev-175.json",
    ...
]
```

**Comment by wjt** [comment]
I fixed this in 6b1c30f2e70e778d17e508ab1e6dc2271747a4de
