### ISSUE TITLE
Support updating PyPI modules

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#74]
Python components which come from https://pypi.org/ should be easy enough to support. There are two cases:

- Apps which specify a single package from PyPI – https://github.com/flathub/org.learningequality.Kolibri is one example.
- Apps which generate a flattened list of packages from a dependency tree using https://github.com/flatpak/flatpak-builder-tools/tree/master/pip

**Comment by wjt** [comment]
The former could be implemented as a degenerate case of the latter: the `kolibri` package, for example, simply has no dependencies beyond Python itself, so the generator would just generate a 1-element list.

**Comment by muelli** [comment]
FTR: [pip-tools](https://github.com/jazzband/pip-tools) seem to be doing relevant work, i.e. they generate sha256 hashes of the downloads for a given package (and their dependencies).

**Comment by proletarius101** [comment]
And it would be good if the node apps have the same feature (automatically updating generated sources): https://github.com/flatpak/flatpak-builder-tools/issues/183
