### ISSUE TITLE
url-pattern documenation and comparison

### ISSUE THREAD

**Issue by wshanks** [flathub-infra/flatpak-external-data-checker#85]
The example `url-pattern` in the README is `https://www.example.com/pub/foo/v(\d+)/foo.tar.gz` but when the checker runs the matched group is treated as the source URL so matching to a single component like `(\d+)` likely isn't what you want to do.

You can instead make the entire url the match group like `(https://www.example.com/pub/foo/v\d+/foo.tar.gz)` but this is also a little weird because the matches are passed to `distutils.version.LooseVersion` to determine the latest url when there are multiple matches. This is probably okay but could do something weird depending on how the URL's on the page are formatted. For example `http://example.com/v0.1/foo.tar.gz` and `http://example.com/v0.1.2/foo.tar.gz` gives an error because it ends up comparing string `"/"` to int `2`.

It is not totally true that you have to match a full url. You can match partial url's because the url is built with `urllib.parse.urljoin(base=url, url=latest_url)` which combines the `url` `x-checker-data` entry with the matched group. If the download url happens to start with the same base as `url` this lets you cut that part off from `url-pattern` which might help in some cases but not always.

I am not sure what the best way to improve things would be. A few suggestions in order of what seems best to me:

* Use the first match that includes the version string found with `version-pattern`
* Just take the first matched group to `url-pattern` rather than parsing them with `LooseVersion` to find the latest.
* Allow `url-pattern` to have a nested group -- the outer group is the url and the inner group is the version pattern inside the url to pass to `LooseVersion` use for sorting

I was wanting to use it for url's like `http://example.com/2.6/2.6.1.tar.gz` where the `url-template` isn't great because it has to be updated each time the minor version changes.

**Comment by gasinvein** [comment]
I think using a single pattern with nested match groups, like `(http://example.com/program-([\d\.]+\d).tar.gz)`, could ultimately solve this, since we'll get versions/urls in pairs and can properly sort urls by corresponding version number.
Yet I don't know how to implement a new checker-data schema for this while keeping compatibility with existing apps.
Any ideas?
